import { describe,expect,test } from 'bun:test';
import { addTask,editOccurrence,getOccurrences,moveOccurrence,reorderOccurrence,toggleComplete,removeOccurrence,mergeData } from './domain';
import { emptyData,type Data,type Draft,type Occurrence } from './model';
import { addDays,weekOf,localDate } from './dates';
const draft:Draft={title:'Skincare',notes:'',time:'08:00',start:'2026-10-05',end:null,weekdays:[0,1,2,3,4,5,6],reminder:null};
function occurrence(data:Data,date='2026-10-05'):Occurrence {const item=getOccurrences(data,date)[0];if(!item)throw new Error('Missing fixture');return item;}
describe('recurrence boundaries',()=>{
  test('Given a bounded series, when resolving end date, then it is inclusive',()=>{const data=addTask(emptyData(),{...draft,end:'2026-10-07'});expect(getOccurrences(data,'2026-10-07')).toHaveLength(1);expect(getOccurrences(data,'2026-10-08')).toHaveLength(0);});
  test('Given a series, when resolving before its start, then there is no occurrence',()=>{const data=addTask(emptyData(),draft);expect(getOccurrences(data,'2026-10-04')).toHaveLength(0);});
  test('Given weekdays, when resolving Saturday and Sunday, then they are absent',()=>{const data=addTask(emptyData(),{...draft,weekdays:[1,2,3,4,5]});expect(getOccurrences(data,'2026-10-10')).toHaveLength(0);expect(getOccurrences(data,'2026-10-11')).toHaveLength(0);});
  test('Given weekends, when resolving Sunday and Monday, then only Sunday appears',()=>{const data=addTask(emptyData(),{...draft,weekdays:[0,6]});expect(getOccurrences(data,'2026-10-11')).toHaveLength(1);expect(getOccurrences(data,'2026-10-12')).toHaveLength(0);});
  test('Given a one-off, when resolving next week, then it does not repeat',()=>{const data=addTask(emptyData(),{...draft,weekdays:[]});expect(getOccurrences(data,'2026-10-12')).toHaveLength(0);});
  test('Given timed and untimed tasks, when resolving, then untimed tasks sort last',()=>{const data=[{...draft,title:'Untimed',time:null},{...draft,title:'Late',time:'21:00'},{...draft,title:'Early',time:'07:30'}].reduce((data,item)=>addTask(data,item),emptyData());expect(getOccurrences(data,'2026-10-05').map(item=>item.title)).toEqual(['Early','Late','Untimed']);});
  test('Given untimed tasks, when moving their manual order, then display order changes',()=>{const data=addTask(addTask(emptyData(),{...draft,title:'A',time:null}),{...draft,title:'B',time:null});const b=getOccurrences(data,'2026-10-05')[1];if(!b)throw new Error('Missing fixture');const reordered=reorderOccurrence(data,b,-1);expect(getOccurrences(reordered,'2026-10-05').map(item=>item.title)).toEqual(['B','A']);});
  test('Given a completed task, when unchecking, then its completion record is unique and reset',()=>{const data=addTask(emptyData(),draft);const checked=toggleComplete(data,occurrence(data));const unchecked=toggleComplete(checked,occurrence(checked));expect(unchecked.completions).toHaveLength(1);expect(occurrence(unchecked).completedAt).toBeNull();});
  test('Given a completed recurrence, when moving it, then completion follows the occurrence',()=>{const data=addTask(emptyData(),draft);const completed=toggleComplete(data,occurrence(data));const moved=moveOccurrence(completed,occurrence(completed),'2026-10-06');expect(getOccurrences(moved,'2026-10-06').filter(item=>item.completedAt)).toHaveLength(1);expect(getOccurrences(moved,'2026-10-06')).toHaveLength(2);});
  test('Given a moved occurrence, when moving it home, then it appears once',()=>{const data=addTask(emptyData(),draft);const moved=moveOccurrence(data,occurrence(data),'2026-10-06');const item=getOccurrences(moved,'2026-10-06').find(item=>item.originalDate==='2026-10-05');if(!item)throw new Error('Missing moved fixture');const home=moveOccurrence(moved,item,'2026-10-05');expect(getOccurrences(home,'2026-10-05')).toHaveLength(1);expect(getOccurrences(home,'2026-10-06')).toHaveLength(1);});
  test('Given a moved recurrence outside its end, when resolving destination, then it is included',()=>{const data=addTask(emptyData(),{...draft,end:'2026-10-05'});const moved=moveOccurrence(data,occurrence(data),'2027-01-01');expect(getOccurrences(moved,'2027-01-01')).toHaveLength(1);});
  test('Given a one-off completion, when moving its date, then the completion remains',()=>{const data=addTask(emptyData(),{...draft,weekdays:[]});const completed=toggleComplete(data,occurrence(data));const moved=moveOccurrence(completed,occurrence(completed),'2026-10-08');expect(getOccurrences(moved,'2026-10-05')).toHaveLength(0);expect(getOccurrences(moved,'2026-10-08')[0]?.completedAt).toBeNumber();});
  test('Given future completions, when splitting a series, then completion identities migrate',()=>{const data=addTask(emptyData(),draft);const completed=toggleComplete(data,occurrence(data,'2026-10-09'));const split=editOccurrence(completed,occurrence(completed,'2026-10-07'),{...draft,start:'2026-10-07',time:'09:00'},'future');expect(getOccurrences(split,'2026-10-09')[0]?.completedAt).toBeNumber();});
  test('Given an override, when future editing on that occurrence, then the new template takes precedence',()=>{const data=addTask(emptyData(),draft);const overridden=editOccurrence(data,occurrence(data),{...draft,title:'Temporary'},'only');const split=editOccurrence(overridden,occurrence(overridden),{...draft,title:'Permanent'},'future');expect(occurrence(split).title).toBe('Permanent');});
  test('Given a recurrence, when deleting one date, then future dates remain',()=>{const data=addTask(emptyData(),draft);const removed=removeOccurrence(data,occurrence(data),'only');expect(getOccurrences(removed,'2026-10-05')).toHaveLength(0);expect(getOccurrences(removed,'2026-10-06')).toHaveLength(1);});
  test('Given distinct device tasks, when merging twice, then no task is duplicated',()=>{const a=addTask(emptyData(),draft);const b=addTask(emptyData(),{...draft,title:'Gym'});const merged=mergeData(a,b);expect(mergeData(merged,b).tasks).toHaveLength(2);});
  test('Given newer deletion, when merging stale data, then the task stays deleted',()=>{const a=addTask(emptyData(),{...draft,weekdays:[]});const task=a.tasks[0];if(!task)throw new Error('Missing fixture');const deleted={...a,tasks:[{...task,deleted:true,updatedAt:task.updatedAt+10}]};expect(getOccurrences(mergeData(deleted,a),'2026-10-05')).toHaveLength(0);});
});
describe('local calendar dates',()=>{
  test('Given a leap year, when adding one day, then February 29 is preserved',()=>{expect(addDays('2028-02-28',1)).toBe('2028-02-29');});
  test('Given year end, when advancing, then the year rolls over',()=>{expect(addDays('2026-12-31',1)).toBe('2027-01-01');});
  test('Given Sunday, when finding Monday week start, then previous Monday is returned',()=>{expect(weekOf('2026-10-11',1)).toBe('2026-10-05');});
  test('Given Sunday, when finding Sunday week start, then the date is unchanged',()=>{expect(weekOf('2026-10-11',0)).toBe('2026-10-11');});
  test('Given a local midnight date, when serializing, then local components are retained',()=>{expect(localDate(new Date(2026,9,5,0,0))).toBe('2026-10-05');});
});
