import { test,expect } from '@playwright/test';
import { openApp,chooseDate } from './helpers';
test('Given a bounded moved occurrence, when editing only it, then a hidden end date does not block saving',async({page})=>{
  await openApp(page);await page.getByRole('button',{name:'Open full task composer'}).click();await page.getByRole('textbox',{name:'What needs to happen?'}).fill('Bounded routine');await page.getByRole('combobox',{name:'Repeat',exact:true}).selectOption('daily');await page.getByRole('textbox',{name:'Ends optional'}).fill('2026-10-07');await page.getByRole('button',{name:'Add task',exact:true}).click();
  await page.getByRole('button',{name:'Edit Bounded routine'}).click();await page.getByRole('button',{name:'Move to another day'}).click();await page.getByRole('textbox',{name:'Move to',exact:true}).fill('2026-10-09');await page.getByRole('button',{name:'Move',exact:true}).click();await chooseDate(page,'2026-10-09');
  await page.getByRole('button',{name:'Edit Bounded routine'}).click();await page.getByRole('textbox',{name:'What needs to happen?'}).fill('Moved and edited');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('checkbox',{name:'Moved and edited, incomplete'})).toBeVisible();await expect(page.locator('[aria-live="polite"]')).toHaveText('Task updated');
});
test('Given whitespace title input, when saving, then a friendly labelled error is shown',async({page})=>{
  await openApp(page);await page.getByRole('button',{name:'Open full task composer'}).click();const title=page.getByRole('textbox',{name:'What needs to happen?'});await title.fill('   ');await page.getByRole('button',{name:'Add task',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('Give this task a name.');await expect(title).toHaveAttribute('aria-invalid','true');await expect(title).toBeFocused();
});
test('Given a moved bounded occurrence, when editing its future series, then native date constraints use the original date',async({page})=>{
  await openApp(page);await page.getByRole('button',{name:'Open full task composer'}).click();await page.getByRole('textbox',{name:'What needs to happen?'}).fill('Bounded routine');await page.getByRole('combobox',{name:'Repeat',exact:true}).selectOption('daily');await page.getByRole('textbox',{name:'Ends optional'}).fill('2026-10-07');await page.getByRole('button',{name:'Add task',exact:true}).click();
  await page.getByRole('button',{name:'Edit Bounded routine'}).click();await page.getByRole('button',{name:'Move to another day'}).click();await page.getByRole('textbox',{name:'Move to',exact:true}).fill('2026-10-09');await page.getByRole('button',{name:'Move',exact:true}).click();await chooseDate(page,'2026-10-09');await page.getByRole('button',{name:'Edit Bounded routine'}).click();await page.getByRole('radio',{name:'This and future occurrences'}).check();
  await expect(page.getByRole('textbox',{name:'Ends optional'})).toHaveAttribute('min','2026-10-05');await page.getByRole('textbox',{name:'What needs to happen?'}).fill('Future edit');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('checkbox',{name:'Future edit, incomplete'})).toBeVisible();
});
