<script lang="ts">
  import { onMount } from 'svelte';
  import type { SupabaseClient } from '@supabase/supabase-js';
  import Sheet from './Sheet.svelte';import Icon from './Icon.svelte';
  import { app,commit,saved,activateAccount } from '#lib/state.svelte.ts';
  import { dataSchema,emptyData,type Settings } from '#lib/model.ts';
  import { mergeData } from '#lib/domain.ts';
  import { resolveConflict } from '#lib/merge.ts';
  import { cloudClient,syncData } from '#lib/cloud.ts';
  import { syncNow,syncState } from '#lib/sync.svelte.ts';
  import { backgroundPushConfigured,enablePush,disablePush } from '#lib/reminders.ts';
  let {onclose}:{onclose:()=>void}=$props();
  let email=$state('');let message=$state('');let confirmDelete=$state(false);let deleteText=$state('');let busy=$state(false);let notifications=$state('Not enabled');let push=$state(false);
  let cloud=$state<SupabaseClient|null>(null);
  function setting<K extends keyof Settings>(key:K,value:Settings[K]){commit({...app.data,settings:{...app.data.settings,[key]:value,updatedAt:Math.max(Date.now(),app.data.settings.updatedAt+1)}});}
  async function changeDefaultReminder(value:string){setting('defaultReminder',value==='none'?null:Number(value));if(value==='none')return;if(!('Notification'in window)){message='Install Folio on your Home Screen to enable notifications on iPhone.';return;}if(Notification.permission==='default')notifications=await Notification.requestPermission();else notifications=Notification.permission;if(notifications!=='granted')message='Allow notifications in browser settings to receive reminders.';}
  onMount(()=>{
    notifications='Notification' in window?Notification.permission:'Unsupported';
    void cloudClient().then(async client=>{cloud=client;const session=await client?.auth.getSession();syncState.email=session?.data.session?.user.email??'';});
    void navigator.serviceWorker?.getRegistration().then(async registration=>{push=!!(await registration?.pushManager.getSubscription());});
  });
  async function signIn(){if(!cloud)return;busy=true;message='';try{const {error}=await cloud.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:location.origin}});if(error)throw error;message='Check your email for a secure sign-in link. Your local tasks stay here.';}catch(error){message=error instanceof Error?error.message:'Couldn’t send the link. Try again.';}finally{busy=false;}}
  async function signOut(){const client=cloud;if(!client)return;busy=true;try{if(push)await disablePush();const {error}=await client.auth.signOut();if(error)throw error;syncState.email='';message='Signed out. Your tasks remain on this device.';}catch(error){message=error instanceof Error?error.message:'Couldn’t sign out. Try again.';}finally{busy=false;}}
  function exportData(){const blob=new Blob([JSON.stringify($state.snapshot(app.data),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`folio-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);message='Your backup has been downloaded.';}
  async function importData(event:Event){const input=event.currentTarget;if(!(input instanceof HTMLInputElement))return;const file=input.files?.[0];if(!file)return;
    if(file.size>5000000){message='This backup is too large. Choose a Folio JSON backup under 5 MB.';return;}
    try{const imported=dataSchema.parse(JSON.parse(await file.text()));commit(mergeData($state.snapshot(app.data),{...imported,ownerId:app.data.ownerId,resetAt:app.data.resetAt}));message='Backup imported. Existing tasks and history were preserved.';}catch(error){message=error instanceof Error?'This isn’t a valid Folio backup. Your current data is unchanged.':'Couldn’t read this backup.';}input.value='';}
  async function switchAccount(){if(!syncState.userId)return;busy=true;try{await activateAccount(syncState.userId);await syncNow();message='Separate account week opened. The previous account’s week is safely archived on this device.';}catch(error){message=error instanceof Error?error.message:'Couldn’t open this account’s week.';}finally{busy=false;}}
  async function notificationAction(){busy=true;try{if(backgroundPushConfigured){if(push)await disablePush();else await enablePush();push=!push;message=push?'Background reminders are enabled for this device.':'Background reminders are off.';}else{if(!('Notification' in window)){message='On iPhone, add Folio to your Home Screen first.';return;}notifications=await Notification.requestPermission();message=notifications==='granted'?'Reminders are enabled while Folio is open.':'You can allow notifications in browser settings.';}}catch(error){message=error instanceof Error?error.message:'Couldn’t update notifications.';}finally{busy=false;}}
  async function deleteData(){if(deleteText!=='DELETE')return;busy=true;try{
    const cleared={...emptyData(),ownerId:app.data.ownerId,resetAt:Math.max(Date.now(),app.data.resetAt+1),settings:$state.snapshot(app.data.settings)};
    commit(cleared,true);await saved();
    if(syncState.email&&cloud&&!syncState.accountMismatch)await syncData(cleared);
    onclose();
  }catch(error){message=error instanceof Error?`Deletion is saved on this device. Cloud reset will retry when connected. ${error.message}`:'Deletion is saved locally. Cloud reset will retry when connected.';}finally{busy=false;}}
</script>
<Sheet title="Your Folio." {onclose}>
  <section class="settings-section"><h3>Appearance</h3><div class="segmented" role="group" aria-label="Appearance">{#each ['system','light','dark'] as theme}<button class:chosen={app.data.settings.theme===theme} aria-pressed={app.data.settings.theme===theme} onclick={()=>{switch(theme){case 'system':setting('theme','system');break;case 'light':setting('theme','light');break;case 'dark':setting('theme','dark');break;}}}>{theme}</button>{/each}</div></section>
  <section class="settings-section"><h3>The week</h3><label class="field">Starts on<select value={String(app.data.settings.weekStart)} onchange={(event)=>setting('weekStart',Number(event.currentTarget.value)===0?0:1)}><option value="1">Monday</option><option value="0">Sunday</option></select></label><label class="toggle-row"><span>Show completed tasks</span><input type="checkbox" checked={app.data.settings.showCompleted} onchange={(event)=>setting('showCompleted',event.currentTarget.checked)}/></label><label class="toggle-row"><span>Hide past completed tasks</span><input type="checkbox" checked={app.data.settings.hidePastCompleted} onchange={(event)=>setting('hidePastCompleted',event.currentTarget.checked)}/></label></section>
  <section class="settings-section"><h3>Reminders</h3><p class="hint">{backgroundPushConfigured?'Optional background push for signed-in devices.':'On-device notifications while the app is open. Background push needs server configuration.'}</p><button class="secondary" disabled={busy} onclick={notificationAction}><Icon name="bell" size={18}/>{push?'Disable background reminders':notifications==='granted'?'Notification settings':'Enable notifications'}</button><label class="field">Default reminder<select value={String(app.data.settings.defaultReminder??'none')} onchange={(event)=>changeDefaultReminder(event.currentTarget.value)}><option value="none">None</option><option value="0">At time</option><option value="5">5 minutes before</option><option value="10">10 minutes before</option><option value="30">30 minutes before</option><option value="60">1 hour before</option></select></label></section>
  <section class="settings-section"><h3>Backup & sync</h3>
    {#if cloud}{#if syncState.email}<p class="hint">Signed in as {syncState.email}</p><div class="button-row"><button class="secondary" disabled={syncState.busy} onclick={syncNow}><Icon name="cloud" size={18}/>{syncState.busy?'Syncing…':'Sync now'}</button><button class="text-button" disabled={busy} onclick={signOut}>Sign out</button></div><p class="hint">{syncState.message}{syncState.lastSync?` · ${syncState.lastSync}`:''}</p>{:else}<p class="hint">Keep your week across devices. No password needed.</p><form onsubmit={(event)=>{event.preventDefault();void signIn();}}><label class="field">Email<input type="email" bind:value={email} placeholder="you@example.com" required autocomplete="email"/></label><button class="secondary" disabled={busy}>Send sign-in link</button></form>{/if}
    {:else}<p class="hint">Your week is saved privately on this device. Cloud sync isn’t configured here. Export a backup to keep a copy.</p>{/if}
    {#if syncState.accountMismatch}<p class="hint">Your previous account’s week will be archived locally, not uploaded to this account.</p><button class="secondary" disabled={busy} onclick={switchAccount}>Open a separate account week</button>{/if}
    {#each app.data.conflicts.filter(row=>!row.resolved) as conflict}<div class="delete-confirm"><p>A task changed while another device removed it.</p><p class="hint">“{conflict.proposed.title}” was preserved for you to review.</p><div class="button-row"><button class="secondary" onclick={()=>commit(resolveConflict(app.data,conflict.id,false))}>Keep task</button><button class="secondary danger" onclick={()=>commit(resolveConflict(app.data,conflict.id,true))}>Apply deletion</button></div></div>{/each}
    <div class="button-row"><button class="secondary" onclick={exportData}><Icon name="download" size={17}/> Export backup</button><label class="secondary file-button"><Icon name="upload" size={17}/> Import backup<input type="file" accept="application/json,.json" onchange={importData}/></label></div>
  </section>
  <section class="settings-section"><h3>Make it feel at home</h3><p class="hint">On iPhone: open Safari’s Share menu, then “Add to Home Screen”. On Android: choose “Install app” from your browser menu.</p><p class="hint">Folio 1.0 · No ads. No tracking. Your week is yours.</p><button class="text-button danger" onclick={()=>confirmDelete=!confirmDelete}>Delete all task data</button>{#if confirmDelete}<p class="hint">This removes all tasks and history{syncState.email?', including your cloud backup':''}. Export a backup first. Type DELETE to confirm.</p><label class="field"><span class="sr-only">Confirm deletion</span><input bind:value={deleteText} placeholder="DELETE"/></label><button class="secondary danger" disabled={deleteText!=='DELETE'||busy} onclick={deleteData}>Permanently delete task data</button>{/if}</section>
  {#if message}<p class="settings-message" role="status">{message}</p>{/if}
</Sheet>
